---
title: "Metabolic Gene Identification"
author: "Paige"
date: "4/13/2020"
output: html_document
---

```{r import.libraries}
library(Seurat)
library(ggplot2)
library(cowplot)
```

```{r import.lists.of.metabolic.genes.and.configure}
#import in the txt lists of genes 
Oxphos <- read.table("gene_lists/oxphos.txt")
#convert to characters  
oxphos <- list("OXPHOS" = Oxphos$V1)
#import in the txt lists of genes 
Glycolysis <- read.table("gene_lists/glycolysis.txt")
#convert to characters  
glycolysis <- list("Glycolysis" = Glycolysis$V1)
#import in the rest of the gene lists and convert to characters
alanine.aspartate <- read.table("gene_lists/alanine.aspartate.glutamate.txt")
alanine.aspartate <- list("Alanine.Aspartate" = alanine.aspartate$V1)
aminoacyl.tRNA.biosynthesis <- read.table("gene_lists/aminoacyl.tRNA.biosynthesis.txt")
aminoacyl.tRNA.biosynthesis <- list("Aminoacyl.tRNA.Biosynthesis" = aminoacyl.tRNA.biosynthesis$V1)
arachadonic.acid <- read.table("gene_lists/arachadonic.acid.txt")
arachadonic.acid <- list("arachadondic.acid" = arachadonic.acid$V1)
arginine.proline <- read.table("gene_lists/arginine.proline.txt")
arginine.proline <- list("arginine.proline" = arginine.proline$V1)
ascorbate.aldarate <- read.table("gene_lists/ascorbate.aldarate.txt")
ascorbate.aldarate <- list("ascorbate.aldarate" = ascorbate.aldarate$V1)
butanoate <- read.table("gene_lists/butanoate.txt")
butanoate <- list("butanoate" = butanoate$V1)
citric.acid <- read.table("gene_lists/citric.acid.txt")
citric.acid <- list("citric.acid" = citric.acid$V1)
cysteine.methionine <- read.table("gene_lists/cysteine.methionine.txt")
cysteine.methionine <- list("cysteine.methionine" = cysteine.methionine$V1)
ester.lipid <- read.table("gene_lists/ester.lipid.metabolism.txt")
ester.lipid <- list("ester.lipid" = ester.lipid$V1)
fatty.acid <- read.table("gene_lists/fatty.acid.txt")
fatty.acid <- list("fatty.acid" = fatty.acid$V1)
fructose.mannose <- read.table("gene_lists/fructose.mannose.txt")
fructose.mannose <- list("fructose.mannose" = fructose.mannose$V1)
galactose <- read.table("gene_lists/galactose.metabolism.txt")
galactose <- list("galactose" = galactose$V1)
glutathione <- read.table("gene_lists/glutathione.metabolism.txt")
glutathione <- list("glutathione" = glutathione$V1)
glycerolipid <- read.table("gene_lists/glycerolipid.metabolism.txt")
glycerolipid <- list("glycerolipid" = glycerolipid$V1)
glycerophospholipid <- read.table("gene_lists/glycerophospholipid.txt")
glycerophospholipid <- list("glycerophospholipid" = glycerophospholipid$V1)
glycine.serine.threonine <- read.table("gene_lists/glycine.serine.threonine.txt")
glycine.serine.threonine <- list("glycine.serine.threonine" = glycine.serine.threonine$V1)
glycosaminoglycan.biosynthesis.chondroitin<- read.table("gene_lists/glycosaminoglycan.biosynthesis.chondroitin.txt")
glycosaminoglycan.biosynthesis.chondroitin <- list("glycosaminoglycan.biosynthesis.chondroitin" = glycosaminoglycan.biosynthesis.chondroitin$V1)
glycosaminoglycan.biosynthesis.heparan <- read.table("gene_lists/glycosaminoglycan.biosynthesis.heparan.txt")
glycosaminoglycan.biosynthesis.heparan <- list("glycosaminoglycan.biosynthesis.heparan" = glycosaminoglycan.biosynthesis.heparan$V1)
glycosaminoglycan.biosynthesis.keratin <- read.table("gene_lists/glycosaminoglycan.biosynthesis.keratin.txt")
glycosaminoglycan.biosynthesis.keratin <- list("glycosaminoglycan.biosynthesis.keratin" = glycosaminoglycan.biosynthesis.keratin$V1)
glyoxylate.dicarboxylate <- read.table("gene_lists/glyoxylate.dicarboxylate.txt") 
glyoxylate.dicarboxylate <- list("glyoxylate.dicarboxylate"= glyoxylate.dicarboxylate$V1)
histidine <- read.table("gene_lists/histidine.txt")
histidine <- list("histidine" = histidine$V1)
linoleic.acid <- read.table("gene_lists/linoleic.acid.txt")
linoleic.acid <- list("linoleic.acid" = linoleic.acid$V1)
lysine.degredation <- read.table("gene_lists/lysine.degradation.txt")
lysine.degredation <- list("lysine.degredation" = lysine.degredation$V1)
pentose.phos <- read.table("gene_lists/pentose.phos.txt")
pentose.phos <- list("pentose.phos" = pentose.phos$V1)
phenylalanine <- read.table("gene_lists/phenylalanine.txt")
phenylalanine <- list("phenylalanine" = phenylalanine$V1)
propanoate <- read.table("gene_lists/propanoate.metabolism.txt")
propanoate<- list("propanoate" = propanoate$V1)
purine <- read.table("gene_lists/purine.metabolism.txt")
purine <- list("purine" = purine$V1)
pyrimidine <- read.table("gene_lists/pyrimidine.metabolism.txt")
pyrimidine <- list("pyrimidine" = pyrimidine$V1)
pyruvate <- read.table("gene_lists/pyruvate.metabolism.txt")
pyruvate <- list ("pyruvate" = pyruvate$V1)
sphingolipid <- read.table("gene_lists/sphingolipid.metabolism.txt")
sphingolipid <- list("sphingolipid" = sphingolipid$V1)
starch.sucrose <- read.table("gene_lists/starch.sucrose.txt")
starch.sucrose <- list("starch.sucrose" = starch.sucrose$V1)
taurine.hypotaurine <- read.table("gene_lists/taurine.hypotaurine.txt")
taurine.hypotaurine <- list("taurine.hypotaurine" = taurine.hypotaurine$V1)
tryptophan <- read.table("gene_lists/tryptophan.txt")
tryptophan <- list("tryptophan" = tryptophan$V1)
tyrosine <- read.table("gene_lists/tyrosine.txt")
tyrosine <- list("tyrosine"= tyrosine$V1)
valine.leucine.isoleucine <- read.table("gene_lists/valine.leucine.isoleucine.txt")
valine.leucine.isoleucine <- list("valine.leucine.isoleucine" = valine.leucine.isoleucine$V1)

#Metabolic Gene List
metabolism.pathways<-list("Glycolysis_Score"=glycolysis, 
                          "Ox_Phos_Score"=oxphos, 
                          "Alanine_Aspartate_Glutamate_Score" = alanine.aspartate, "Aminoacyl_tRNA_Biosynthesis_Score" = aminoacyl.tRNA.biosynthesis, "Arachadonic_Acid_Score" = arachadonic.acid, "Arginine_Proline_Score" = arginine.proline, "Ascorbate_Aldarate_Score" = ascorbate.aldarate, "Butanoate_Score"= butanoate, "Citric_Acid_Score" = citric.acid, "Cysteine_Methionine_Score" = cysteine.methionine, "Ester_Lipid_Score" = ester.lipid, "Fatty_Acid_Score" = fatty.acid, "Fructose_Mannose_Score" = fructose.mannose, "Galactose_Score" = galactose, "Glutathione_Score" = glutathione, "Glycerolipid_Score" = glycerolipid, "Glycerophospholipid_Score" = glycerophospholipid, "Glycine_Serine_Threonine_Score" = glycine.serine.threonine, "Glycosaminoglycan_Biosynthesis_Chondroitin_Score" = glycosaminoglycan.biosynthesis.chondroitin, "Glycosaminoglycan_Biosynthesis_Herapan_Score" = glycosaminoglycan.biosynthesis.heparan, "Glycosaminoglycan_Biosynthesis_Keratin_Score" = glycosaminoglycan.biosynthesis.keratin, "Glyoxylate_Dicarboxylate_Score" = glyoxylate.dicarboxylate, "Histidine_Score" = histidine, "Linoleic_Acid_Score" = linoleic.acid, "Lysine_Degradation_Score" = lysine.degredation, "Pentose_Phos_Score" = pentose.phos, "Phenylalanine_Score" = phenylalanine, "Propanoate_Score" = propanoate.metabolism, "Purine_Score" = purine, "Pyrimidine_Score" = pyrimidine, "Pyruvate_Score" = pyruvate, "Sphingolipid_Score" = sphingolipid, "Starch_Sucrose_Score" = starch.sucrose, "Taurine_Hypotaurine_Score" = taurine.hypotaurine, "Tryptophan_Score" = tryptophan, "Tyrosine_Score" = tyrosine, "Valine_Leucine_Isoleucine_Score" = valine.leucine.isoleucine
                          )
```

```{r import.Norm.BRCA.data}
load("seurat-objects/norm.brca.integrated.epithelial.Rda")
Norm.BRCA <- norm.brca.integrated.epithelial
```
```{r add.module.scores}
#set the DefaultAssay 
DefaultAssay(Norm.BRCA)<-"RNA"

#Add scores and plotting for the metabolism gene lists via a for loop
metabolism.vln.plots<-list()
metabolism.box.plots<-list()
for (i in 1:length(metabolism.pathways)){
  Norm.BRCA <- AddModuleScore(object = Norm.BRCA,
                              features = metabolism.pathways[[i]],
                              name = paste(names(metabolism.pathways[i])),
                              assay = "RNA")
  
  print(paste("Calculating",names(metabolism.pathways[i])))
  
  metabolism.vln.plots[i] <- VlnPlot(object = Norm.BRCA,
                    features = paste(names(metabolism.pathways[i]),"1",sep = ""),
                    group.by = "Cell.Type",
                    split.by = "Status",
                    pt.size = 0,
                    combine = FALSE)
  
  metabolism.box.plot.matrix<-FetchData(Norm.BRCA, 
                                        c(paste(names(metabolism.pathways[i]),"1",sep = ""),
                                          "Cell.Type", "Status"))
  
  
  print(head(metabolism.box.plot.matrix))
  
  metabolism.box.plots[[i]] <- ggplot(metabolism.box.plot.matrix,
                                    aes(x=metabolism.box.plot.matrix[,2],
                                        y=metabolism.box.plot.matrix[,1],
                                        fill=metabolism.box.plot.matrix[,3]))+
                                geom_boxplot()+
                                ggtitle(paste(names(metabolism.pathways[i])))+
                                xlab("") + ylab("Gene Score")+
                                theme_classic()+
                                theme(legend.title = element_blank())
}

plot_grid(plotlist = metabolism.vln.plots,ncol = 2)
plot_grid(plotlist = metabolism.box.plots,ncol = 2)


FeaturePlot(object = Norm.BRCA, features = "OXPHOS_Score1")
FeaturePlot(object = glycolysis.Norm.BRCA, features = "Glycolysis_Score1")

test<-VlnPlot(oxphos.Norm.BRCA, 
        features = "OXPHOS_Score1",
        group.by = "Cell.Type",
        split.by = "Status",
        pt.size = 0)

```
