---
title: "Splitting Seurat Objects by Individual"
author: "Paige"
date: "4/10/2020"
output: html_document
---

```{r load.packages}
#install.packages("Seurat")
library(Seurat)
library(dplyr)
library(reshape2)
library(SeuratData)
```


## Load in seurat objects

```{r load.objects}
#HCI001
load("/Users/paigehalas/ph-future-phd/pdx-norm-brca-integration-project/seurat-objects/hci001.seurat3.object.Rda")
#HCI002
load("/Users/paigehalas/ph-future-phd/pdx-norm-brca-integration-project/seurat-objects/hci002.seurat3.object.Rda")
#HCI010
load("/Users/paigehalas/ph-future-phd/pdx-norm-brca-integration-project/seurat-objects/hci010.seurat3.object.Rda")
#Norm/BRCA
load("/Users/paigehalas/ph-future-phd/pdx-norm-brca-integration-project/seurat-objects/norm.brca.integrated.epithelial.Rda")
```

##Relabel all of the Seurat objects 
```{r rename.Seurat.objects}
HCI001 <- p01.cc.updated
HCI002 <- p02.updated
HCI010 <- p10.updated
NormBRCA <- norm.brca.integrated.epithelial
```

```{r split.NormBRCA.by.individual}
NormBRCA.Split <-SplitObject(NormBRCA, split.by = "individual")
```

